name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2

      - run: zig build run -- --help
      - run: zig build test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2

      # cross compile
      - run: zig build -Dtarget=x86_64-macos --prefix-exe-dir x86_64-macos
      - run: zig build -Dtarget=aarch64-macos --prefix-exe-dir aarch64-macos
      - run: zig build -Dtarget=x86_64-linux-gnu --prefix-exe-dir x86_64-linux-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu --prefix-exe-dir aarch64-linux-gnu

      # upload
      - uses: actions/upload-artifact@v4
        with:
          name: ci-zig-out
          path: |
            ./zig-out/x86_64-linux-gnu
            ./zig-out/aarch64-macos

  run:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        include:
          - os: ubuntu-latest
            path: x86_64-linux-gnu
          - os: macos-15
            path: aarch64-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: ci-zig-out
      
      - run: tree

      - run: |
          chmod +x ./zig-out/${{ matrix.path }}/ttm
          ./zig-out/${{ matrix.path }}/ttm --help
