name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2

      - run: zig build -Dtarget=x86_64-macos --prefix-exe-dir ttm-${{ github.ref_name }}-x86_64-apple-darwin
      - run: zig build -Dtarget=aarch64-macos --prefix-exe-dir ttm-${{ github.ref_name }}-aarch64-apple-darwin
      - run: zig build -Dtarget=x86_64-linux-gnu --prefix-exe-dir ttm-${{ github.ref_name }}-x86_64-linux-gnu
      - run: zig build -Dtarget=aarch64-linux-gnu --prefix-exe-dir ttm-${{ github.ref_name }}-aarch64-linux-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: release-zig-out
          path: |
            ./zig-out/ttm-${{ github.ref_name }}-x86_64-apple-darwin
            ./zig-out/ttm-${{ github.ref_name }}-aarch64-apple-darwin
            ./zig-out/ttm-${{ github.ref_name }}-x86_64-linux-gnu
            ./zig-out/ttm-${{ github.ref_name }}-aarch64-linux-gnu

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: release-zig-out
          path: dist

      - run: |
          for dir in dist/*; do
            tar -czf dist/$(basename $dir).tar.gz -C $dir .
          done
      - run: shasum -a 256 *.tar.gz > checksums.txt
        working-directory: dist

      - run: |
          cat <<'EOF' | envsubst > release.md
          # Release ${{ github.ref_name }}
          EOF

      - uses: softprops/action-gh-release@v2
        with:
          body_path: release.md
          files: |
            dist/checksums.txt
            dist/*.tar.gz
